FROM golang:1.16-alpine
RUN apk add build-base

# copy the code rather than using volume for production
RUN mkdir /go/src/tagger
COPY ./ /go/src/tagger

WORKDIR /go/src/tagger

RUN go mod tidy
RUN go mod download

RUN go install
CMD ["tagger"]
