version: "3.4"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  api:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DBNAME=tagger_db_dev_01
      - REDIS_PORT=6379
    volumes:
      - ./:/go/src/tagger:delegated
    links:
      - redis
    stdin_open: true # docker run -i
    tty: true        # docker run -t
  api_prod:
    depends_on:
      - redis
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8081"