version: "3.4"
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  api:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DBNAME=tagger_db_dev_01
    volumes:
      - ./:/go/src/tagger:delegated
    stdin_open: true # docker run -i
    tty: true        # docker run -t

